global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Logging;
global using MidjourneyAPI.Dtos;
global using MidjourneyAPI.Options;
global using Newtonsoft.Json;
global using System;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;